modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="tax_future_citizen"
version="1.0.0"
displayName="Tax' Future Citizen"
displayURL="https://www.curseforge.com/minecraft/mc-mods/taxfuturecitizen"
logoFile="logo.png"
credits="Written by Taknax and LeonX"
authors="Taknax, LeonX"
description="Future Citizen is a Minecraft moodifikation aims to bring the future."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tax_future_citizen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration